# Generated by Django 3.0.4 on 2020-03-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('cid', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=7)),
                ('access_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('tid', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('txt', models.CharField(max_length=20)),
            ],
        ),
    ]
